spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin_sayak25
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#JPA Settings

  jpa.hibernate.ddl_auto: update

#Login User Details

  security:
    user:
      name: sayakUser
      password: Sayak1

#Swagger Settings

springdoc:
  packages-to-scan: com.think.rest_demo
  paths-to-match: /vendor/**,/books/**



#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/dashboard"
  endpoint:
    health:
      show-details: always
    shutdown:
      access: UNRESTRICTED

  info:
    env:
      enabled: true    

dummyService:
  port: 8081
  address: 127.0.0.1

server:
  shutdown: graceful

info:
  app:
    name: RestDemoApplication
    description: Book and Vendor App built by Sayak!!
    version: 1.0.0

logging:
  level:
    '[com.think.rest_demo.controller]': DEBUG
    