spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin_sayak25
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#JPA Settings

  jpa.hibernate.ddl_auto: update

#Login User Details

  security:
    user:
      name: sayakUser
      password: Sayak1




management:
  endpoints:
    web:
      exposure:
        include: "health,beans,metrics"
      base-path: "/dashboard"
  endpoint:
    health:
      show-details: always

dummyService:
  port: 8081
  address: 127.0.0.1
